meta:
  title: "Poll based futures in Rust"
  thumbnail:
  description:
  siteName: fsmaxb.github.io/cppugka-vortrag-rust-futures
  sns:
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
      - cpp
      - c
      - rust
      - protobuf
      - json
      - cmake
      - bash
      - diff
    plugins:
      - line-numbers
    theme: twilight
  chart: false
  math: false
extends:
  js:
  css: ./style.css
  webpack:
build:
  ssr: true
